#pragma once

#define SIGNALFORGE_VERSION_MAJOR 1
#define SIGNALFORGE_VERSION_MINOR 0
#define SIGNALFORGE_VERSION_PATCH 0
#define SIGNALFORGE_VERSION_STRING "1.0.0"
#define SIGNALFORGE_BUILD_DATE __DATE__
#define SIGNALFORGE_BUILD_TIME __TIME__
